// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twawgwqkljzmjlpvnmtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3YXdnd3FrbGp6bWpscHZubXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjYwNjgsImV4cCI6MjA2NDU0MjA2OH0.hymr-PRO5GKnl3CTuLiICdx9WgQV7UDQWIrj9083dBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);